module.exports = {
  C: "c",
  CPP: "cpp",
  PYTHON: "python",
  JAVA: "java",
  NODEJS: "nodejs",
  RUBY: "ruby",
  PROMPTV1: "promptv1",
  PROMPTV2: "promptv2",
  GO: "go",
  SWIFT: "swift",
  TYPESCRIPT: "typescript",
  MULTIFILE: "multifile",
  SQLITE3: "sqlite3",
};
